#!/bin/bash
echo "===== Network Monitor ====="
echo " Date : $(date)"
echo "===== Internet Connection ====="
if ping -c 1 google.com &> /dev/null; then
echo "Internet is connected ✓"
else 
echo "Internet is not connected ✗"
fi
servers=("github.com" "google.com" "youtube.com")
for server in ${servers[@]}; do
    if ping -c 1 $server &>/dev/null; then
        echo "$server is reachable"
    else
        echo "$server is not reachable"
    fi
done

ip=$(hostname -I | awk '{print $1}')
dns=$(cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}')

echo "===== Network Info ====="
echo "IP Address: $ip"
echo "DNS Server: $dns"
